ToDo/ToDo.Web.Mvc/Models/CreateItemModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDo.Web.Mvc.Models
{
    public class CreateItemModel
    {
        [StringLength(256, MinimumLength = 5)]
        public string Description { get; set; }
    }
}

ToDo/ToDo.Web.Mvc/Models/ErrorViewModel.cs
namespace ToDo.Web.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDo/ToDo.Web.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDo.Web.Mvc.Models;

namespace ToDo.Web.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDo/ToDo.Web.Mvc/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using ToDo.Application.Dtos.Item;
using ToDo.Application.Interfaces;
using ToDo.Domain.Entities;
using ToDo.Domain.Interface;
using ToDo.Web.Mvc.Models;

namespace ToDo.Web.Mvc.Controllers
{
    public class ItemController : Controller
    {
        protected IItemService service;

        public ItemController(IItemService service)
        {
            this.service = service;
        }
        public async Task<IActionResult> Index()
        {
            var items = await service.GetItemsAsync();

            return View(items);
        }

        public IActionResult Create()
        {
            return View();
        }

        

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Description")] ItemRequestDTO itemRequestDTO)
        {
            if (ModelState.IsValid)
            {
                await service.CreateItemAsync(itemRequestDTO);

                return RedirectToAction(nameof(Index));
            }  

            return View();
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            if (Id != null)
            {
                await service.EditItemAsync(Id);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid Id)
        {
            if (Id != null )
            {
                await service.DeleteItemAsync(Id);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

ToDo/ToDo.Web.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDo/ToDo.Web.Mvc/Views/Item/Create.cshtml
@model ToDo.Web.Mvc.Models.CreateItemModel


@{
    ViewData["Title"] = "Criar item";
}



<div class="col-md-4">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Description" class="control-label">Nome da tarefa</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Criar tarefa" action="Create" class="btn btn-primary" />
        </div>
    </form>
</div>


<div>
    <a asp-action="Index">Voltar</a>
</div>

ToDo/ToDo.Web.Mvc/Views/Item/Index.cshtml
@model IEnumerable<ToDo.Application.Dtos.Item.ItemResponseDTO >

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Adicionar tarefa</a>
</p>

<table id="item" class="table">
    <thead>
        <tr class="">
            <th>Descrição</th>
            <th>Data de criação</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="display: none;">@item.Id</td>
                <td>@item.Description</td>
                <td>@item.CreatedAt.ToString("dd/MM/yyyy HH:mm")</td>
                <td><input asp-action="Edit" type="checkbox" disabled @(item.Done ? "checked" : "") />@(item.Done ? " Done" : " ToDo") </td>
                <td>
                    <a asp-controller="Item" asp-action="Edit" asp-route-id="@item.Id"> Alterar Status</a>
                    <a asp-controller="Item" asp-action="Delete" asp-route-id="@item.Id"> Excluir</a>
                </td>

            </tr>
        }
    </tbody>
</table>

<script>
    function add() {
        window.location.href = ''
    }
</script>

ToDo/ToDo.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo.Web.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo.Web.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo.Web.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">ToDo List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDo.Web.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>